# Generated by Django 4.1.1 on 2022-10-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Magnet',
            new_name='magnet',
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(verbose_name='review date'),
        ),
    ]
